stages:
  data_ingestion:
    cmd: python src/pipeline/stage_01_data_ingestion.py
    deps:
      - src/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/

  prepare_base_model:
    cmd: python src/pipeline/prepare_base_model_02.py
    deps:
      - src/pipeline/prepare_base_model_02.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - LEARNING_RATE
      - INCLUDE_TOP
      - WEIGHTS
      - CLASSES
      - FREEZE_ALL
      - FREEZE_TILL
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/pipeline/model_training_03.py
    deps:
      - src/pipeline/model_training_03.py
      - src/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/
      - artifacts/prepare_base_model
    params:
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
      - IMAGE_SIZE
    outs:
      - artifacts/training/model.h5
      - artifacts/label_encoder.pkl


  evaluation:
    cmd: python src/pipeline/evaluation_04.py
    deps:
      - src/pipeline/evaluation_04.py
      - config/config.yaml
      - artifacts/data_ingestion/
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false
    figures:
      - figures/evaluation/