artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_url: "https://github.com/KonstantinosTsoumas/dog-breed/tree/main/artifacts"
    local_data_file: artifacts/data_ingestion/train.zip
    unzip_dir: artifacts/data_ingestion


prepare_base_model:
    root_dir: Path
    base_model_path: Path
    updated_base_model_path: Path
    params_image_size: list
    params_learning_rate: float
    params_include_top: bool
    params_weights: str
    params_classes: int
