artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_url: "https://github.com/KonstantinosTsoumas/dog-breed/tree/main/artifacts"
    local_source_file: artifacts/train.zip
    local_data_file: artifacts/train.zip  # Can later be switched to dev/prod environment if needed.
    unzip_dir: artifacts/data_ingestion


prepare_base_model:
    root_dir: Path
    base_model_path: Path
    updated_base_model_path: Path
    params_image_size: list
    params_learning_rate: float
    params_include_top: bool
    params_weights: str
    params_classes: int


prepare_callbacks:
    root_dir: Path
    tensorboard_root_log_dir: Path
    checkpoint_model_filepath: Path


training:
    root_dir: Path
    trained_model_path: Path
    updated_base_model_path: Path
    training_data: Path
    params_epochs: int
    params_batch_size: int
    params_is_augmentation: bool
    params_image_size: list
