artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_url: "https://github.com/KonstantinosTsoumas/dog-breed/tree/main/artifacts"
    local_source_file: artifacts/train.zip
    local_data_file: artifacts/train.zip  # Can later be switched to dev/prod environment if needed.
    unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5


prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5


training:
  root_dir: artifacts/data_ingestion
  trained_model_path: artifacts/training/model.h5
